export { HeardComponent } from './heard/heard.component';
export { AjudaComponent } from './ajuda/ajuda.component';
export { MenuComponent } from './interno/menu/menu.component';
export { TopoComponent } from './interno/topo/topo.component';
export { LoginComponent } from './externo/login/login.component';
export { GerarComponent } from './gerar/gerar.component';
export { BonificacaoComponent } from './bonificacao/bonificacao.component';
export { ServicoComponent } from './servico/servico.component';
export { SituacaoComponent } from './situacao/situacao.component';
